= COMP603 (Compiler Design)

== May 9

IMPORTANT: If you haven't already done so by now, install git and frontends, and setup your course repository.

=== Pre-quiz (How much theory do you know?)

NOTE: Don't worry, this isn't graded (but please do it anyway)

Pretend we're taking a closed-book exam. Answer these questions in a file called +prequiz.txt+ in your repo.

. What is the difference between a set, a bag, and a sequence?
. What is a language in terms of sets and sequences?
. What is a compiler?
. What is the derivative of a language?
. What is a regular expression?
. What is a finite automaton?
. What is the difference between an NFA and a DFA?
. What is a grammar?
. What is the difference between LL(k) and LR(k)?
. What is the difference between recursive descent parsing, shift-reduce parsing and parser combinators?
. What is a visitor?
. Name some optimizations.
. What is an abstract syntax tree?

== May 7

=== Introduction

. What's your name?
. Why did you pick computer science?
. What do you still want to learn and/or what do you aspire to do after graduation?
. Tell us something nobody else knows about you.

=== https://raw.githubusercontent.com/lawrancej/COMP603-2014/master/COMP603SyllabusLawrance.docx[Syllabus (Word document)]

* Even though you may develop mobile/web apps or games, compilers are relevant to your career.
* Writing compilers give you superpowers: (e.g., http://www.robovm.org/[RoboVM], https://github.com/kripken/emscripten/wiki[emscripten])

=== Install Git and frontends

Windows:: https://code.google.com/p/gitextensions/downloads/list[Install Git Extensions, MSysGit and KDiff3].
+
NOTE: Stick to the default settings, but when asked, *choose OpenSSH (not PuTTY)*.

Mac OS X:: http://rowanj.github.io/gitx/[Install GitX-dev].
+
NOTE: https://developer.apple.com/xcode/downloads/[XCode developer tools] ships with git; otherwise, http://git-scm.com/download/mac[install the latest git from here].

Linux:: http://git-scm.com/download/linux[Install git] using your package manager. http://sourceforge.net/projects/qgit/[QGit, a git frontend] may also be available for your distribution.
+
NOTE: Don't forget to use +sudo+ with your package manager.

=== Setup your course repository

IMPORTANT: You must use LeopardSecure, not LeopardGuest.

All platforms:: Paste this into your terminal (Git Bash on Windows):
+
----
curl https://raw.githubusercontent.com/lawrancej/COMP603-2014/master/starterupper.sh | sh
----
+
NOTE: Press +Insert+ to paste in Git Bash.
